### PR TITLE
typeaheadjs options per minLength request

### LINKED ISSUE #314: Add minLength support using typeahead
Is there any way to use minLength in typeahead which minimum character length needed before suggestions start getting rendered?

### PR DESCRIPTION
**Pull request by gdibble**
resolves #314 

i did not bump version herein

### CODE REVIEW

**Comment by gdibble** [comment]
@timschlechter  :+1: tested here, ready for review

**Comment by lucknerjb** [comment]
Taking a look at this one tonight, it'll be merged soon :-)

**Comment by gdibble** [comment]
btw you'll notice I added functionality while maintaining backwards compatibility with previous api

**Comment by lucknerjb** [comment]
Closing PR as merging it would be too complicated. Keeping the proposed config structure though

**Pull request closed without merging**
