### PR TITLE
Add scss file

### PR DESCRIPTION
**Pull request by brunowego**
With `wiredep` task I can overwide the plugin and inject only I need. See:

``` js
wiredep: {
  app: {
    overrides: {
      'bootstrap-tagsinput': {
        main: [
          './dist/bootstrap-tagsinput.js',
          './dist/bootstrap-tagsinput.scss',
        ]
      }
    }
  }
}
```

Reference of #303

### CODE REVIEW

**Comment by ismailbaskin** [comment]
:thumbsup:

**Comment by Uriel29** [comment]
+1

**Comment by andregeraldi** [comment]
Show!

**Comment by brunowego** [comment]
Have chance to merge?

**Pull request closed without merging**
