### PR TITLE
Regression fix. Input value was still displayed after typeahead selectio...

### PR DESCRIPTION
**Pull request by A----**
Commit 03e6ce0785268d6f89aa11152f8cda815b95b1f0 did a regression overhere where input wasn't clear after a typeahead selection.
Fixed it by returning '' instead of the original value.

I'm using bootstrap3-typeahead 3.1.1.

@austinhappel Could you try and confirm that this still works for you?

This might be related to this issue #331 that I actually can't reproduce but heh.

### CODE REVIEW

**Comment by austinhappel** [comment]
At first glance, this _should_ work. The error I was seeing was caused by `updater` returning `undefined`. This fix returns `''` which should be enough to resolve the issue as well. 

I'd like to investigate this tonight if you don't mind. Could you give me ~24 hours to validate this and perhaps provide an example of the issue so you can repro it later? If I don't respond after 24hrs you can do as you please. 

Thanks for keeping me in the loop :)

**Comment by austinhappel** [comment]
@A---- I haven't had time to test this regression in detail (too busy as of late). I don't want to block this merge - so it has my stamp of approval. 

I don't foresee any issues from the commit itself, but if problems come up, I'll make sure to keep you in the loop on any PR's I may present to resolve the issues.

**Comment by kouk** [comment]
Hi guys, any chance this will be merged?

**Comment by kouk** [comment]
@timschlechter

**Comment by xplicit** [comment]
This fix does not work for me with bootstrap3-typeahead. I am using objects as tags, so maybe this fix works olny with strings, I'll investigate it further.

**Comment by xplicit** [comment]
I'm sorry, I did not read the first message and thought this commit fixes #331. So the previous message should be read as "This commit does not fix #331".

**Comment by milotoor** [comment]
+1

I'm also having issues with 03e6ce0, though I think my problem is just *slightly* different from @A----'s. I am using Bootstrap 2 with Typeahead 2.2.2. In my instance, `this.map[text]` returns an object, and the Typeahead takes this and enters it as the value of the select. So the resulting content of the select is a badge with my term in it, followed by `[object Object]`...

An empty string should solve my problem.

**Pull request closed without merging**
