### PR TITLE
Free input with object items

### PR DESCRIPTION
**Pull request by perecedero**
Hey Tim!
I'am using your amazing plugin for a personal project and made some modifications to be able to use freeInput with object items.

My idea was to provide a schema from which to clone the items, and a function for setting the string in the new object as desired.  it works like this:

``` javascript
    var elt = $('input');
    elt.tagsinput({
        itemValue: 'id',
        itemText: 'name',
        freeInputSchema: {id:null, name:null, other:'default value'},
        freeInputSchemaSet: function(item, value){item.id = value; item.name =  value;}
    });
    elt.tagsinput( 'add', 'pepe'); //< adds  {id:pepe, name:pepe, other:'default value'},
```

I appended the new tests to  **_input_with_object_items.tests.js.**_

I also refactored object tests (some of them were testing the same thing), and updated test/index.html to reflect the karma config file.

Please let me know if you need more info about this changes,
Regards, Ivan

### CODE REVIEW

**Comment by Amitesh** [comment]
I love to see this pull request merged with main stream.
+1

Thanks @perecedero for adding this feature.

**Comment by lucknerjb** [comment]
@perecedero Thanks for the PR. I'll review it tonight

**Comment by smisch** [comment]
+1

Just tested this PR and it works perfectly with only one little flaw: 

1. focus input
2. write a new "free" tag, that is not already in typeahead's list
3. press enter
4. new free tag is correctly added, input is cleared
5. blur input
6. previously added tag is written back into input by typeahead

This happens because typeahead didn't register that the .tt-input got cleared and "updates" it back to it's internal value (this.query) upon blur. 

To solve add the following line in `TagsInput.prototype.add` (line 88): 
````
      // convert string to object using freeInputSchema
      if (typeof item === "string" && self.objectItems) {
        var defaultItem = $.extend({}, self.options.freeInputSchema);
        self.options.freeInputSchemaSet(defaultItem, item);
        item = defaultItem;

        // ADD THIS LINE: tell typeahead that the current value is empty
        self.$input.typeahead("val", "")
      }

**Comment by popod** [comment]
update ? I d'like to see this pull request merged with main stream too. tanks

**Pull request closed without merging**
