### PR TITLE
Add possibility skip "change" event after "add", "remove", "removeAll

### PR DESCRIPTION
**Pull request by wawanawna**
…" methods

### CODE REVIEW

**Comment by wawanawna** [comment]
Hi, first of all thx for great lib.

Sometimes we need to disable 'change' event because it may trigger our handlers many times if we 'add' many values sequentially. Better to have ability disable 'change' event and manage it outside of lib code.

**Comment by otisg** [comment]
+1 for this.

**Comment by lucknerjb** [comment]
@wawanawna Thanks for the PR! Could you add some test support for this though please?

**Comment by wawanawna** [comment]
Hello, thx for quick response. Added test.

**Review by Jjhhd6r — COMMENTED** [review]
These things are happening on a company phone I have too, and I am being purseued. Last time I asked for help my sim card was cloned by someone close by.how can I protect myself? #

**Pull request merged**
