### PR TITLE
Created CONTRIBUTING guidelines

### PR DESCRIPTION
**Pull request by k-nut**
I started to work on a change a couple of days back and was not sure what to run. I think I figured it out by checking the gruntfile but I also wrote it down for future developers. I think it would be very valuable to have these explanations (or something similar) in the repository.

### CODE REVIEW

**Comment by k-nut** [comment]
I did a rebase and force push. `Pull request` is now singular as you asked for. Thank you for looking into this!

**Comment by k-nut** [comment]
@lucknerjb is everything good with this and you can merge it now? Or is there anything that I should still change?

**Comment by lucknerjb** [comment]
@k-nut I wanted to add a few more things, which is why I haven't merged it yet. It is a good idea and something I wanted to get done eventually.

**Comment by k-nut** [comment]
If there is anything I can help with don't hesitate to ask!

**Comment by k-nut** [comment]
any update on this?

**Pull request closed without merging**
